language: scala

jdk:
  - oraclejdk8
  - openjdk11

scala:
  - 2.12.8
  - 2.13.0-RC1

env:
  global:
    # PGP_PASSPHRASE
    - secure: "BYC1kEnHjNrINrHYWPGEuTTJ2V340/0ByzqeihLecjoZ75yrjWdsh6MI1JEUWgv5kb+58vLzib21JfnjsPK6Yb2bSXuCFCsEtJNh6RJKgxkWlCOzfTSh5I2wl7PCjRClRL6gseX2uTSvFjL4Z//pmxwxeXlLp7voQe4QAUq1+sE="
    # SONA_USER
    - secure: "OpBwPc1GNvauageYOH3RscAa7wpZxgpmqDz15aigIKLNWzAhAtVUx0MleZ8rQeoqml6nrAvlnzuVHjKL2lVcjMPpjUis7bcQ5UAGK7tZK8x+qZNQxXmpXu8+pENwQA2yFaqt/xy7K5jFOrHJHTRxcPnyVG1yKakPWz53PPYUwbc="
    # SONA_PASS
    - secure: "Xw7rI/qlML1nD2e2XwlakkhKAWNGZKqqE+Q3ntTvFpfHryl7KLCvVzJ4LIavnL6kGJaWOgy9vlSoEWn5g9nqHSfE31C/k5pY5nTMAKiwiJzfAS+r0asKXW2gmKhwtcTBkqyLVOZLCJSPVlFRQyfBJHY+Fs0L3KWcnMQgtBlyDhU="
  matrix:
    # The empty SCALAJS_VERSION will only compile for the JVM
    - SCALAJS_VERSION=
    - SCALAJS_VERSION=0.6.27
    - SCALAJS_VERSION=1.0.0-M7

matrix:
  exclude:
    - jdk: openjdk11
      env: SCALAJS_VERSION=0.6.27
    - jdk: openjdk11
      env: SCALAJS_VERSION=1.0.0-M7

script: 
  - admin/build.sh

before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" | xargs rm
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt
